# Copy etcd binary
COPY --from=etcd /usr/local/bin/etcd /usr/local/bin/etcd
COPY --from=etcd /usr/local/bin/etcdctl /usr/local/bin/etcdctl

# Create symbolic link for data directory
RUN ln -sf /var/www/html/.devpanel/milvus/volumes/etcd /etcd

# Copy Supervisor config for etcd service
COPY supervisor/etcd.conf /etc/supervisor/conf.d/etcd.conf
